### PR TITLE
Create FairingCameraPatch.cfg

### PR DESCRIPTION
**Pull request by craidler**
Adds a SpaceX style wide angle camera to all 5 (expansion covered) stock fairings.

### CODE REVIEW

**Comment by craidler** [comment]
Maybe you could remove the "downwards" cam ... if I have time I will figure out which property it is.

**Comment by linuxgurugamer** [comment]
What do you mean by "downwards" cam?

**Comment by linuxgurugamer** [comment]
Still waiting to know what you mean by the "downwards" cam

**Comment by linuxgurugamer** [comment]
I tried this, it doesn't work.  Feel free to update and resubmit

**Pull request closed without merging**
